### ISSUE TITLE
no annotations found

### ISSUE THREAD

**Issue by 55jr55** [julihoh/pdf_annotation_fix#11]
lost annotations in attached file but web app says none found
[REYNOLDS 30X36 A1-1st-windows.pdf](https://github.com/julihoh/pdf_annotation_fix/files/12786677/REYNOLDS.30X36.A1-1st-windows.pdf)

**Comment by julihoh** [comment]
If the webapp can't find the annotations, there is nothing I can do unfortunately. Sorry
