### ISSUE TITLE
ERROR: page annotations is not an array

### ISSUE THREAD

**Issue by fbarretto** [julihoh/pdf_annotation_fix#2]
Hi,

After successfully cloning the repo and installing rust, I'm trying to run a pdf which has some annotations added in preview that doesn't appear when I open the pdf. Crashed pdf file is inside the project folder (and is attached here).
[crash.pdf](https://github.com/julihoh/pdf_annotation_fix/files/6785197/crash.pdf)

`cargo run -- crash.pdf test.pdf`

But I'm getting

```
barretto@virus pdf_annotation_fix % cargo run -- crash.pdf test.pdf
    Finished dev [unoptimized + debuginfo] target(s) in 0.05s
    Running `target/debug/pdf_annotation_fix crash.pdf teste.pdf`
Error: page annotations is not an array

Caused by:
    An object does not have the expected type
```

Any hints on how to get over this error or is it a bug?

[crash.pdf](https://github.com/julihoh/pdf_annotation_fix/files/6785204/crash.pdf)

**Comment by julihoh** [comment]
I just pushed what I think could be a fix for this problem. I also attached the successfully converted to this comment. Please let me know if the pdf is fixed as expected.

[fixed.pdf](https://github.com/julihoh/pdf_annotation_fix/files/6785620/fixed.pdf)

Cheers

**Comment by fbarretto** [comment]
Yes, indeed fixed.pdf file seems to be correct. I'll try to pull and check if it runs fine. 

Cheers

**Comment by fbarretto** [comment]
Problem solved.

Thanks!
