### ISSUE TITLE
Rectangular annotations are not detected

### ISSUE THREAD

**Issue by fluxtransistor** [julihoh/pdf_annotation_fix#3]
Although visible in Preview, the red dashed rectangles I have added to the below document do not appear in other PDF editors. Please let me know if this is not the intended function, but unfortunately the web-app does not detect the annotations
[suppdocA.pdf](https://github.com/julihoh/pdf_annotation_fix/files/7799857/suppdocA.pdf)
.

**Comment by julihoh** [comment]
Interesting. However, as long as they are displayed in preview as they should, this tool can't really help. This tool can only help in cases where annotations are not displayed in preview _anymore_.

Does this answer your question?
